### ISSUE TITLE
Other volcas?

### ISSUE THREAD

**Issue by ryanramage** [waterjump/volca-share#4]
Hey, I just picked up a bass and found this project. Amazing work! 

Just curious if this can be done with other volcas? eg I have a keys - do you think it can dump and load patches?

**Comment by waterjump** [comment]
Hey Ryan,

I'm really glad you like the project.  Thanks!

I've been kicking around the idea of supporting patches for the Keys because that seems to be the next most popular Volca.  But there's a lot of overhead and refactoring that would need to be done for VolcaShare to support that, so I haven't taken any steps towards it.  I imagine that feature would take several weeks of work, which means nights an weekends for me because this is a hobby project.  If I ever undertake that change, I'll let you know.

Even though VolcaShare is designed to send MIDI signals to the Volca Bass, the Volca Keys' MIDI implementation uses the same control change numbers as the Bass, so if you want, you can manipulate controls on the new/edit patch form for the bass, and the keys would be affected.  It's important to note that the control changes are mapped to different controls on the keys than they are on the bass.  For example, changing CC40 on the bass changes the octave.  On the keys, CC40 changes the voice.  You can find the midi implementations charts here:
[Volca Bass MIDI Implementation Chart](http://i.korg.com/uploads/Support/USA_volcabass_MIDI_Chart_E.pdf)
[Volca Keys MIDI Implementation Chart](http://i.korg.com/uploads/Support/USA_volcakeys_MIDI_Chart_E.pdf)

I hope that helps.

**Comment by ryanramage** [comment]
Thank you so much!!! That is the info I needed. My question was poorly worded, it was if more around if the keys can support control changes. I can do the work myself 😁. Thanks for the detailed answer!

**Comment by waterjump** [comment]
Hi @ryanramage.  I've launched [Volka Keys support](https://www.volcashare.com/keys/patch/new) on VolcaShare.  It's beta for now so please do not broadcast this on reddit / message boards etc.  You can access the new patch for in a link in the footer.  Created patches will only show up on your "My Patches" page if you are logged in.  Enjoy.  Please give me any feedback you may have.  :-]

**Comment by ryanramage** [comment]
Hey that is awesome. I will keep it quiet. I just logged in and see the editor. Looks great. 

Just at work now, but will give it a go this evening. Thanks!
